server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG


facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    # clientId: bd1c0a783ccdd1c9b9e4
    # clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    clientId: 1e23fd1ad849f81fa36f
    clientSecret: 294feb7dacf8b317b36bb800b4be08675a5edaf1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

u2ware:
  client:
    # clientId: bd1c0a783ccdd1c9b9e4
    # clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    clientId: confidential
    clientSecret: secret
    accessTokenUri: http://localhost:8081/oauth/token
    userAuthorizationUri: http://localhost:8081/oauth/authorize
    clientAuthenticationScheme: form
  # resource:
  #   userInfoUri: 


com:
  u2ware:
    sample:
      oauth2:
        authorization:
          AuthorizationServerConfig:
            jwt:
              enabled: true
              # openssl genrsa -out jwt.pem 2048
              # openssl rsa -in jwt.pem
              privateKey: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIEpAIBAAKCAQEAse1tjWVVYcbeofjMILI92gce5B9zKh/HA71tU5R+5KqqZ+S0
                yG9+ICCwTSgcgfpgXMLC9hDM2d8SNE7sGEaFjRTPX01acieiPZVWvELat7Oxf7XW
                hkZ6iT9xxFKb0YgnyZ6AkW4eAg/emI/JUAb4ERYHC8b/Ud5qwXvPasKKNBhbijz3
                njCsIEIRpe8L43gvkmaA7Eyxj4Agu+dt0j6fiqDaxIHxxI6lTrufrWG1CaVvKAgd
                18vlxbFg//6lLLTVOkKrnibijD9u7SRNfdx3NDgsetAZeDvoYAotqv7VDCKuIl3V
                yDX6q/cE58BLWo0mCYOtyeU1EDXmRMDWN8+E+QIDAQABAoIBAQCpTr6CX7yhb/WF
                txO2wSUuBLyWYn7ZxKdBnc0cTR96RBQnDHAikkU4GSLqKJMH89IiMooGT/I+F5Bh
                CgCLEQAgQX8atqasHZ66bxK7zfoF+A2c8tERsJsFYsPFBr6S4bbKmfLJcDlJyQQN
                tDTh29/NkmJeCJwHsVdwiXnTow6ThkmbTIay/UEO3UxLcS+zTw62hQReakEj2nQW
                l44adLtoXdiAGWvfqRi7vdLXxaIrDq3IUItDUK7m93iS2VZ/QvGJEIXDE1VnfHfq
                0sEPr7v9ZQSv4I5vhPqL/yTKNWuPZVVgjNktqkF+OwuEIQBECByu3IFfllmfpWaL
                rZklL4UBAoGBAO0Kv5Sj0sbuuf80JOKTM3sgvaAQejq5GVJn3IjTDdP6BiFozAtq
                zn/Fpi2Gw2cfneZcPopCMxqcs9W1IIczjmuswCcZNnXG9nMg1aPtxGm+WmnrWGAV
                mBDa1khXlhnANJstlhjP+qkj3m2hB6ielyNzfwrrP+yivcvkIBeZWgApAoGBAMAo
                Wuuna4g4tKoqJFyChxVqYN8z21U9wJmyc8jFNyiY9yI5950g02XTV5N6OFwELvS4
                6TY8XHb1Xy5Lhlp+77aSa1QwG4z727veZDTJ1R/8bRV4iBw8JSavw+ol14+j1yG8
                ISGTD4VaGchNZNmGPZVDn+WgOaSm6UVJkKhXeLhRAoGBAIzRRtCxpeTCK0Kdoo/r
                bLjn0V7GiyZZkd5vjwbFgsB8FqpATH832ybyru760RhxIueXwxt1ilBz6S265XEM
                Qr5aqOhRRRYgtYXdaq1w8a70A1hLFHw4N9dDeesOBUCU+2t4YGOrIjja8ydjc15L
                oHPSCBXffWFBqMj4Y8xBMMNJAoGAOYtcPvnyH+crY1IfdXy5S1aCEBWNd2d4yA5C
                0jsNG6FDUQKe/nUYGYRC061kN1ohXbQKUu2cmxs8F7cSUwN0ce5DKgEGHyBFW2ts
                Asr2gg+r8yQXTq1MStuUBgizFxbvk/Cs00sg+MRUuEFFFEc5JfwMZE2pNX+ul8tC
                AMfBJSECgYBk/E4XDBhkLNob9lTbEm48GWQ7b1uPQe+ZDk8tSOWVh3r53jWdPgbr
                IA9g4t5kKKbifMRwu+oRJrquyJmqiGt2tkHxdEBm8pbnJYgAIhMH5dBGkvRr9TPy
                NTNG7RtZMLOwmOmmPXX9nuk39BYO1yuliOxBU5T+KVXk7mqOPWtY2Q==
                -----END RSA PRIVATE KEY-----
              # openssl rsa -in jwt.pem -pubout
              publicKey: |
                -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAse1tjWVVYcbeofjMILI9
                2gce5B9zKh/HA71tU5R+5KqqZ+S0yG9+ICCwTSgcgfpgXMLC9hDM2d8SNE7sGEaF
                jRTPX01acieiPZVWvELat7Oxf7XWhkZ6iT9xxFKb0YgnyZ6AkW4eAg/emI/JUAb4
                ERYHC8b/Ud5qwXvPasKKNBhbijz3njCsIEIRpe8L43gvkmaA7Eyxj4Agu+dt0j6f
                iqDaxIHxxI6lTrufrWG1CaVvKAgd18vlxbFg//6lLLTVOkKrnibijD9u7SRNfdx3
                NDgsetAZeDvoYAotqv7VDCKuIl3VyDX6q/cE58BLWo0mCYOtyeU1EDXmRMDWN8+E
                +QIDAQAB
                -----END PUBLIC KEY-----
            