server:
  port: 8888

# management:
#   security:
#     enabled: false

spring:
  profiles:
    active: native
  # cloud:
  #   config:
  #     server:
  #       native:
  #         searchLocations: file:///C:/app-config


